/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    BlogSummary: typeof import('./src/components/BlogSummary.vue')['default']
    DropdownBtn: typeof import('./src/components/DropdownBtn.vue')['default']
    DropdownSelection: typeof import('./src/components/DropdownSelection.vue')['default']
    GalleryCard: typeof import('./src/components/GalleryCard.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MarkdownDisplay: typeof import('./src/components/MarkdownDisplay.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    ProfileIcon: typeof import('./src/components/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
}
